site_name: myapi
site_description: An API
repo_url: https://github.com/mxdmedia/my-api
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/mxdmedia">mxdmedia</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
